name: detect-unused-secrets

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Detect unused secrets
        uses: nearform/github-action-detect-unused-secrets@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
